version: '3'

tasks:
  init:
    cmds:
      - git submodule init
      - git submodule update

  deps:
    cmds:
      - cd lib/graphiql && yarn install
      - cd lib/playground && yarn install
      - cd lib/voyager && yarn install
      - cd lib/altair && yarn install
    concurrent: true

  build:
    cmds:
      - cd lib/graphiql && yarn build
      - cd lib/playground && yarn build
      - cd lib/voyager && yarn build
      - cd lib/altair && yarn build
    concurrent: true

  kotlin:
    cmds:
      - ./gradlew build

  all:
    cmds:
      - task init
      - task deps
      - task build
      - task kotlin
